---
version: '3'
services:
  postgresql:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: "developer"
      POSTGRES_DB: "notesapp"
      POSTGRES_PASSWORD: "supersecretpassword"
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ../.data/postgresql:/var/lib/postgresql/data/pgdata
