---
version: '3'
services:
  postgresql:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "companydb"
      POSTGRES_PASSWORD: "secret"
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./.data/postgresql:/var/lib/postgresql/data/pgdata
